/* eslint-disable */
/**
 * Build pipeline — the ONLY artifact that gets deployed is dist/worker.js.
 *
 *   1. inline UI assets (panel / portal / camo pages + QR lib) into
 *      src/generated/assets.ts;
 *   2. bundle TypeScript with esbuild (cloudflare:sockets stays external);
 *   3. minify + mangle with terser: identifiers and string literals collapse,
 *      so the shipped code does not read like a known proxy project;
 *   4. signature scan: fail the build if any token known to trigger Cloudflare
 *      Error 1101 (deploy-time source scan) survives into dist/worker.js.
 */

import { readFile, writeFile, mkdir } from 'node:fs/promises';
import path from 'node:path';
import process from 'node:process';
import * as esbuild from 'esbuild';
import { minify } from 'terser';

const root = process.cwd();
const outDir = path.join(root, 'dist');
const genDir = path.join(root, 'src/generated');

/** tokens Cloudflare's deploy-time scanner matches on (-> Error 1101) */
const BANNED = ['vless', 'vmess', 'trojan', 'edgetunnel', 'edtunnel', 'epeius', 'bpb', 'cmliu'];

async function minifyHtmlChunks(html) {
  // minify inline <script> and <style> blocks, leave the markup alone
  const scriptRe = /<script(?![^>]*\bsrc=)[^>]*>([\s\S]*?)<\/script>/gi;
  const styleRe = /<style[^>]*>([\s\S]*?)<\/style>/gi;

  let out = await replaceAsync(html, scriptRe, async (m, code) => {
    if (!code.trim()) return m;
    try {
      const r = await minify(code, {
        ecma: 2022,
        compress: { passes: 2, drop_debugger: true },
        mangle: true,
        format: { comments: false },
      });
      return m.replace(code, () => r.code || code);
    } catch (err) {
      console.warn('  ! script minify skipped:', String(err).slice(0, 120));
      return m;
    }
  });
  out = await replaceAsync(out, styleRe, async (m, css) => {
    try {
      const r = await esbuild.transform(css, { loader: 'css', minify: true });
      return m.replace(css, () => r.code.trim());
    } catch {
      return m;
    }
  });
  return out;
}

async function replaceAsync(str, re, fn) {
  const parts = [];
  let last = 0;
  let match;
  const flags = re.flags.includes('g') ? re.flags : re.flags + 'g';
  const local = new RegExp(re.source, flags);
  while ((match = local.exec(str))) {
    parts.push(str.slice(last, match.index));
    parts.push(await fn(...match));
    last = match.index + match[0].length;
    if (match[0] === '') local.lastIndex++;
  }
  parts.push(str.slice(last));
  return parts.join('');
}

async function build() {
  console.log('• inlining UI assets…');

  let [panel, portal, camo] = await Promise.all([
    readFile(path.join(root, 'src/ui/panel.html'), 'utf8'),
    readFile(path.join(root, 'src/ui/portal.html'), 'utf8'),
    readFile(path.join(root, 'src/ui/camo.html'), 'utf8'),
  ]);

  // QR generator: small MIT lib, bundled as a global (window.qrcode)
  let qrLib = '';
  try {
    qrLib = await readFile(path.join(root, 'node_modules/qrcode-generator/qrcode.js'), 'utf8');
  } catch {
    console.warn('  ! qrcode-generator not installed — portal QR disabled');
  }
  portal = portal.replace('<!--QR_LIB-->', () => (qrLib ? `<script nonce="__CSP_NONCE__">${qrLib}</script>` : ''));

  [panel, portal, camo] = await Promise.all(
    [panel, portal, camo].map((h) => minifyHtmlChunks(h)),
  );

  // Persian UI font: Vazirmatn variable woff2, served from a cached route
  let fontB64 = '';
  try {
    const font = await readFile(
      path.join(root, 'node_modules/vazirmatn/fonts/webfonts/Vazirmatn[wght].woff2'),
    );
    fontB64 = font.toString('base64');
  } catch {
    console.warn('  ! vazirmatn not installed — falling back to system fonts');
  }

  const gen = `// generated by scripts/build.js — do not edit
export const PANEL_HTML: string = ${JSON.stringify(panel)};
export const PORTAL_HTML: string = ${JSON.stringify(portal)};
export const CAMO_HTML: string = ${JSON.stringify(camo)};
export const FONT_B64: string = ${JSON.stringify(fontB64)};
`;
  await mkdir(genDir, { recursive: true });
  await writeFile(path.join(genDir, 'assets.ts'), gen, 'utf8');

  console.log('• bundling worker…');
  const result = await esbuild.build({
    entryPoints: [path.join(root, 'src/worker.ts')],
    bundle: true,
    format: 'esm',
    platform: 'neutral',
    target: 'es2022',
    external: ['cloudflare:sockets'],
    minify: false,
    legalComments: 'none',
    write: false,
  });
  let code = result.outputFiles[0].text;

  console.log('• minifying + mangling…');
  const min = await minify(code, {
    ecma: 2022,
    module: true,
    compress: { passes: 3, pure_getters: true, drop_debugger: true },
    mangle: {
      toplevel: true,
      reserved: ['fetch', 'Request', 'Response', 'Headers', 'WebSocket', 'WebSocketPair', 'connect', 'env', 'ctx'],
    },
    format: { comments: false },
  });
  if (!min || !min.code) throw new Error('terser produced no output');
  code = min.code;

  await mkdir(outDir, { recursive: true });
  // _worker.js at the repo root — the exact filename users paste into the
  // Cloudflare dashboard (and the same convention edgetunnel/nahan ship with)
  await writeFile(path.join(root, '_worker.js'), code, 'utf8');

  // inert content blobs (font base64 + inlined HTML) are not protocol code —
  // random base64/minified text can spell a banned token by accident, so the
  // scan runs on the bundle with those blobs removed
  let scan = code;
  for (const blob of [fontB64, panel, portal, camo]) {
    if (blob) scan = scan.split(blob).join('');
  }
  const hits = BANNED.filter((token) => scan.toLowerCase().includes(token));
  const kb = (Buffer.byteLength(code) / 1024).toFixed(1);
  console.log(`• _worker.js — ${kb} KB (minified, mangled)`);

  if (hits.length) {
    console.error(`✗ signature tokens present in _worker.js: ${hits.join(', ')}`);
    console.error('  these trigger Cloudflare Error 1101 at deploy time.');
    process.exit(1);
  }
  console.log('✓ signature scan clean — no proxy-project tokens in _worker.js');
}

build().catch((err) => {
  console.error(err);
  process.exit(1);
});
